# Generated by Django 5.1.6 on 2025-02-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Product_Disc', models.CharField(max_length=400)),
                ('Publish_Date', models.DateField()),
            ],
        ),
    ]
